In [1]:
import numpy as np
import pandas as pd

#Series of 1-D array

In [3]:
s = pd.Series([10,20,30,40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [9]:
pop = pd.Series([1444 , 1393 , 323 , 278],
                index = ["India","China","USA","Indonesia"],
                name = "population_millions"
               )

In [10]:
print(pop)

India        1444
China        1393
USA           323
Indonesia     278
Name: population_millions, dtype: int64

In [8]:
print(pop[pop>500])

India    1444
China    1393
Name: population_millions, dtype: int64

In [12]:
q1 = pd.Series({"laptops":120,"phone":340,"tablets":77})
q2 = pd.Series({"phones":44,"laptops":474,"watches":73})
print(q1+q2)

laptops    594.0
phone        NaN
phones       NaN
tablets      NaN
watches      NaN
dtype: float64

#Data frames

In [14]:
df = pd.DataFrame({
    "name": ["Aushu","Bill","chen","Dev","Emu"],
    "dept": ["IT","HR","IT","Finance","HR"],
    "salary":[52000,48000,47999,75000,50000],
    "city":["Delhi","Mumbai","Surat","Agra","Delhi"]
})

In [15]:
print(df)

    name     dept  salary    city
0  Aushu       IT   52000   Delhi
1   Bill       HR   48000  Mumbai
2   chen       IT   47999   Surat
3    Dev  Finance   75000    Agra
4    Emu       HR   50000   Delhi

In [16]:
print(df.shape)

(5, 4)

In [17]:
print(list(df.columns))

['name', 'dept', 'salary', 'city']

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   dept    5 non-null      object
 2   salary  5 non-null      int64
 3   city    5 non-null      object
dtypes: int64(1), object(3)
memory usage: 292.0+ bytes

In [19]:
df.describe()

             salary
count      5.000000
mean   54599.800000
std    11524.031421
min    47999.000000
25%    48000.000000
50%    50000.000000
75%    52000.000000
max    75000.000000

In [22]:
raw = pd.DataFrame({
    "order_id":["1001","1002","1003"],
    "amount":["2500","1800","1700"]
})

In [24]:
print(raw["amount"].sum())

250018001700

In [25]:
clean = raw.copy()

In [26]:
clean["order_id"] = pd.to_numeric(clean["order_id"])
clean["amount"] = pd.to_numeric(clean["amount"])

In [27]:
print(clean.sum())

order_id    3006
amount      6000
dtype: int64

In [28]:
print(clean["amount"].sum())

6000

In [29]:
df

    name     dept  salary    city
0  Aushu       IT   52000   Delhi
1   Bill       HR   48000  Mumbai
2   chen       IT   47999   Surat
3    Dev  Finance   75000    Agra
4    Emu       HR   50000   Delhi

In [31]:
people = df.set_index("name")

In [32]:
people

          dept  salary    city
name
Aushu       IT   52000   Delhi
Bill        HR   48000  Mumbai
chen        IT   47999   Surat
Dev    Finance   75000    Agra
Emu         HR   50000   Delhi

In [33]:
print(people.loc["Aushu"])

dept         IT
salary    52000
city      Delhi
Name: Aushu, dtype: object

In [34]:
print(people.loc[["Aushu"],["salary"]])

       salary
name
Aushu   52000

In [35]:
print(people.iloc[0])

dept         IT
salary    52000
city      Delhi
Name: Aushu, dtype: object

In [37]:
print(people.iloc[0:3],[0,2])

      dept  salary    city
name
Aushu   IT   52000   Delhi
Bill    HR   48000  Mumbai
chen    IT   47999   Surat [0, 2]

In [42]:
print(people[people["salary"]<49000])

     dept  salary    city
name
Bill   HR   48000  Mumbai
chen   IT   47999   Surat

In [46]:
print(people[(people["dept"] == "IT") & (people["salary"] < 49000)])

     dept  salary   city
name
chen   IT   47999  Surat

In [48]:
print(people.query("dept == 'IT'"))

      dept  salary   city
name
Aushu   IT   52000  Delhi
chen    IT   47999  Surat

#Missing data

In [52]:
messy = pd.DataFrame({
    "product":["pen","Book","Bag","lamp","Mug"],
    "price":[20,np.nan,850,1200,np.nan],
    "rating":[4.1,4.5,np.nan,4.5,3.9]
})

In [53]:
messy

  product   price  rating
0     pen    20.0     4.1
1    Book     NaN     4.5
2     Bag   850.0     NaN
3    lamp  1200.0     4.5
4     Mug     NaN     3.9

In [54]:
messy.isna().sum()

product    0
price      2
rating     1
dtype: int64

In [55]:
filled  = messy.copy()

In [64]:
filled["price"] = filled["price"].fillna(filled["price"].mean())

In [65]:
filled["rating"] = filled["rating"].fillna(filled["rating"].median())

In [66]:
print(filled)

  product  price  rating
0     pen    4.1     4.1
1    Book    4.5     4.5
2     Bag    4.3     4.3
3    lamp    4.5     4.5
4     Mug    3.9     3.9